const CONSTANTS = {
  TICK: 16.66,

  CANVAS_WIDTH: 900,
  CANVAS_HEIGHT: 600,
  SHIP_WIDTH: 40,
  SHIP_HEIGHT: 40,
  SPEED: 250,

  SHOOTING_SPEED: 5,
  FIRE_INTERVAL: 300,

  BULLET_HEIGHT: 5,
  BULLET_WIDTH: 2,

  INVADERS_HEIGHT: 25,
  INVADERS_WIDTH: 60,
  INVADERS_ROWS: 5,
  INVADERS_COLS: 8,
  INVADERS_GAP: 5,
  INVADER_SHOOTING_FREQUENCY: 800,

  KEYS: {
    LEFT: 37,
    RIGHT: 39,
    ENTER: 13,
    SPACE: 32
  },

  SCORE_STEP: 10
};

export default CONSTANTS;
